server:
  port: 7072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service 
          uri: lb://user-service
          predicates:
          - Path=/api/user/**
